### ISSUE TITLE
FR: Reset of data

### ISSUE THREAD

**Issue by cybertza** [yhur/arduplot#12]
Hi I have used the plugin a few times, but find it frustrating with the ESP32.

I have a situation where if the unit boots it creates a ton of useless items,
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/20600538/205794166-1de51b65-cba3-4bdb-8ea9-eb9d6ec8e1a3.png">
```
Can't convert b'status:' to float. it's zeroed out
Can't convert b'temp:' to float. it's zeroed out
Can't convert b'Change' to float. it's zeroed out
Can't convert b':' to float. it's zeroed out
Can't convert b'N' to float. it's zeroed out
Can't convert b'Change' to float. it's zeroed out
```
my serial output looks like this and works fine in serial plotter:
`Delay : 250             Last : 2725             Reading :  2750     status: 0      Change : Y              Change (old-new): -25`

<img width="213" alt="image" src="https://user-images.githubusercontent.com/20600538/205795075-0905f225-0fd9-420e-a665-e6039cd7b356.png">

Anyway, So in short, and understading that these are 2 seperate issues, but if the ESP reboots it will drop information on the serial as part of the bootloader, this also confuses the metrics, so the one request is that a "clear or reset" button be available.

**Comment by cybertza** [comment]
I also see that you currently just handle the values, did a quick sample of the example you provide
https://wokwi.com/projects/350261873610850898
<img width="1513" alt="image" src="https://user-images.githubusercontent.com/20600538/205796435-dea41179-9b48-4c7c-8685-33f435cc3abb.png">


So i assume you just use the 2 values as floats, but what you could do if you wanted to would be the following, is if you have a b then assume a key value pair, with a delimiter of '\t' || ':' || '=' and try to link them that way.

that said, its just an idea, but a few tweaks could go a long way for adoption.

**Comment by yhur** [comment]
@cybertza 
This is to provide the compatible tool with the Arduino IDE serial plotter, so it assumes the serial out put the series of numbers. And it can handle more than two numbers. 

What you suggested is one way of doing it, but I'd rather keep it as is since, I want it to be compatible to the Arduino IDE's plotter at this time.

Thank you again.

**Comment by cybertza** [comment]
Delay : 250 Last : 2725 Reading : 2750 status: 0 Change : Y Change (old-new): -25

Ok thank you, the recomendation is to improve compatibility with the ard serial monitor, as the arduino serial monitor works with the line as shown above.


<img width="923" alt="image" src="https://user-images.githubusercontent.com/20600538/205876865-a0f95b2a-cee6-458c-ba05-fb5c75079795.png">

**Comment by yhur** [comment]
Hmm. Interesting. I didn't know there is a feature like this with Arduino IDE.

So when the serial outputs like this, it will pick up the legend.
```
data1 : value1 data2 : value2 data3 : value3 ...
```

By the way, do you know why there are redundant color boxes?

**Comment by yhur** [comment]
@cybertza 
Since the Arduino IDE functionality doesn't seem to be explainable for the consistency and clarity for now, I would like to wait till it gets cleared, and need to close this for now.
