### ISSUE TITLE
Wrong output with delay less than 1s

### ISSUE THREAD

**Issue by semka95** [yhur/arduplot#4]
If i set delay less than 1000 in loop, for example:
```c
void loop() {
    readDHT22();
    Serial.printf("%.1f\t %.1f\n", temperature, humidity);
    delay(100);
}
```
plot displays this:
![2021-12-13_19h45m57s_screenshot](https://user-images.githubusercontent.com/4162760/145853694-b3d904b5-acd7-4f32-a42c-76cde606a19c.png)
Is it how it supposed to work, or is it a bug?

**Comment by yhur** [comment]
Nope, it's not the way designed. On my Mac, it is working fine like this even with 10 ms.

![스크린샷 2021-12-14 오전 3 10 04](https://user-images.githubusercontent.com/13171662/145865565-2cdcb606-8855-4414-80cb-e542dea23a48.png)

I haven't tired it with this short interval on Windows, so I am not sure with the Windows python environment.

**Comment by semka95** [comment]
That's interesting. I'm using linux, not windows. I will try to debug this. If I find out something I will let you know.

**Comment by yhur** [comment]
That will be great. Thanks

**Comment by yhur** [comment]
@semka95 
I'm closing this for now. If you need, please re-open it. Thanks.
