### ISSUE TITLE
Installation on Windows 10

### ISSUE THREAD

**Issue by 8JupiterMoll8** [yhur/arduplot#6]
Hallo,
 i'm trying to install Arduplot on my Windows machine for using it with Platformio.
I have some understanding Problems with step 2:

copy ~/.platformio/penv/lib/python3.9/site-packages/arduplot/filter_plotter.py to either
```
<Project>/monitor
```

1. Right now I have Arduplot download with pip.
2. it is located in folder C:\Users\Jupiter Moll\AppData\Local\Programs\Python\Python310\Lib\site-packages\arduplot
3. In this folder i have three files:  __init__.py , filter_plotter.py and plotserialdata.py

Question should i copy this whole folder into :
```
~/.platformio/penv/lib/python3.9/site-packages/
```
?
 And what does this mean?
```
<Project>/monitor
```
Should i creat an new folder in my platformio project with  the name ``` monitor ```.
An what should i put here?

Thx>

**Comment by yhur** [comment]
There are three ways to configure. 
1. configure every time you create a pio project
2. configure your platform like esp8266 or esp32  
3. or you just configure globally by setting an environment variable.

For 1, you create a folder 'monitor' under your pio project folder, and copy ~/.platformio/penv/lib/python3.9/site-packages/arduplot/filter_plotter.py script to that folder.

For 2, you create the  ~/.platformio/platform/espressif8266/monitor folder and copy  ~/.platformio/penv/lib/python3.9/site-packages/arduplot/filter_plotter.py to that folder. If you're using other platform like esp32, then create the  ~/.platformio/platform/espressif32/monitor folder and copy to that folder.

For 3, you set the environment variable as in README.md in the Windows way.

So, you're correct for the option 1. Create the monitor folder and copy the python script.

Hope this helps.

**Comment by yhur** [comment]
Since this answer is reflected on the README.md, it can be closed.
