### ISSUE TITLE
Y-Axis

### ISSUE THREAD

**Issue by markdegrootnl** [yhur/arduplot#8]
Is it possible to set the Y-Axis scale? Would be nice.

**Comment by yhur** [comment]
I haven’t thought about that. 

What would be the usage scenario?

**Comment by markdegrootnl** [comment]
For instance, say I'm logging a temperature sensor:
![Schermafbeelding 2022-03-10 om 12 35 32](https://user-images.githubusercontent.com/3601019/157654099-3b6d0266-d7ac-4106-8d06-f184904ebeca.png)
Everything happens on the top of the screen.

Now if I change https://github.com/yhur/arduplot/blob/764e67a893401835fd53c481c18336e966a339fc/src/arduplot/plotserialdata.py#L100 to `plt.axis([0, width, 23, 26])` it becomes a lot more useful:

![Schermafbeelding 2022-03-10 om 12 38 55](https://user-images.githubusercontent.com/3601019/157654511-09c9a2ed-71b5-47d8-a607-f4c15e785f5d.png)

Obviously the min and max values would have to be configurable using command line options, just like the width parameter.

**Comment by markdegrootnl** [comment]
Awesome!

The added benefit is that if you don't supply ymin and ymax, it autoscales even nicer then it did before.
