### ISSUE TITLE
Feature request: Add option to have x-axis represent time

### ISSUE THREAD

**Issue by lemonkey** [yhur/arduplot#9]
Great work first of all, this is much appreciated. 👍 

Are there plans to allow the x-axis to update over time, like the Arduino Serial plotter does?

Right now the x-axis never updates. It just ranges from 0 to the initially defined width.

For signals that don't change much over time, it's useful to know the approximate time since startup that the most recent value plotted occurred.

Or at a minimum allow the mouseover tool tip to show the time value for the value of the x-coordinate if it's too difficult to scale the x-axis.

Perhaps allow for a specific log format to represent (time (e.g., millis()), value) to be plotted so that independent of when the plotter was launched, the x-axis can represent the time values being logged.

**Comment by yhur** [comment]
Thank you for your feedback.

For the moment, there is no plan on this, but I’ll consider this for the enhancement in future.

**Comment by yhur** [comment]
Closing it for now.
